### ISSUE TITLE
IIC2233/contenidos 404

### ISSUE THREAD

**Issue by larosi** [IIC2233/syllabus-2019-2#634]
Hola,
Los contenidos del curso están privados? no puedo acceder a ellos [https://github.com/IIC2233/contenidos](https://github.com/IIC2233/contenidos)
quería revisar los jupyter de clases y threads

**Comment by entamburini** [comment]
Hola! :)

Los contenidos se reinician cada semestre y dejan de ser públicos. Si necesitas los contenidos de este semestre me puedes mandar un mail para mandarlos por ese medio :)

Saludos!

**Comment by larosi** [comment]
muchas gracias, cual es el mail?

**Comment by entamburini** [comment]
iic2233@ing.puc.cl
✌️
